[package]
name = "abc170"
version = "0.1.0"
authors = ["hem6 <hem6@users.noreply.github.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"
text_io = "*"
itertools = "*"
superslice = "*"

[profile.release]
lto = true
panic = 'abort'
